# Site settings
title: Artist Name | Portfolio
email: artist@example.com
description: >-
  Portfolio website showcasing the artwork and exhibitions of Artist Name.
baseurl: "/artist-portfolio"  # Only if your repo is not using a custom domain
url: "https://jrwxd.github.io/artist-portfolio"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  artwork:
    output: true
    permalink: /artwork/:path/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "artwork"
    values:
      layout: "artwork"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - .git/
