name: Deploy Jekyll site

on:
  push:
    branches:
      - main  # Change if your main branch is different
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build Jekyll site
        run: bundle exec jekyll build
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/jrwxd/artist-portolio.git
          git checkout -B gh-pages
          git add -A
          git commit -m "Deploy: $(date)"
          git push -f origin gh-pages
